/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.30.12-2-g9464f334b (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.30.12-2-g9464f334b"
#endif
#define SDL_REVISION_NUMBER 0
